import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Providers as AuthProviders } from "./(auth)/providers";
import { Providers } from "./providers";

// FONTS ***********************************************************************************************************************************
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// METADATA ********************************************************************************************************************************
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	icons: { icon: "/convex.svg" },
};

// ROOT ************************************************************************************************************************************
export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Providers>
					<AuthProviders>
						<header className="p-2 border-b-1">
							<Button variant="ghost">
								<Link href="/">Home</Link>
							</Button>
							<Button variant="ghost">
								<Link href="/admin">Admin</Link>
							</Button>
						</header>
						<main className="p-10">{children}</main>
					</AuthProviders>
				</Providers>
			</body>
		</html>
	);
}
