import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Providers } from "./providers";

// FONTS ***********************************************************************************************************************************
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

// METADATA ********************************************************************************************************************************
export const metadata: Metadata = {
	title: "convex-workos",
	description: "Generated by create next app",
	icons: { icon: "/convex.svg" },
};

// ROOT ************************************************************************************************************************************
export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} antialiased`}>
				<Providers>
					<header className="p-2 border-b-1">
						<Button variant="ghost">
							<Link href="/">Home</Link>
						</Button>
						<Button variant="ghost">
							<Link href="/admin">Admin</Link>
						</Button>
					</header>
					<main className="p-10">{children}</main>
				</Providers>
			</body>
		</html>
	);
}
